"""initial schema

Revision ID: c09fa1120861
Revises: 
Create Date: 2026-09-25 04:45:17.810322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c09fa1120861'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('qb_reference_clips',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('clip_id', sa.String(), nullable=False),
    sa.Column('qb_name', sa.String(), nullable=False),
    sa.Column('source_url', sa.String(), nullable=False),
    sa.Column('license_note', sa.String(), nullable=False),
    sa.Column('timestamp_range', sa.String(), nullable=False),
    sa.Column('camera_angle', sa.String(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('validation_status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clip_id')
    )
    op.create_table('uploads',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('video_path', sa.String(), nullable=False),
    sa.Column('fps', sa.Float(), nullable=True),
    sa.Column('validation_status', sa.String(), nullable=False),
    sa.Column('rejection_reason', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('analysis_results',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('upload_id', sa.String(), nullable=False),
    sa.Column('matched_qb_name', sa.String(), nullable=False),
    sa.Column('matched_clip_id', sa.String(), nullable=True),
    sa.Column('overall_similarity_score', sa.Float(), nullable=False),
    sa.Column('confidence_level', sa.String(), nullable=False),
    sa.Column('coaching_notes', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['matched_clip_id'], ['qb_reference_clips.clip_id'], ),
    sa.ForeignKeyConstraint(['upload_id'], ['uploads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('phase_boundaries',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('upload_id', sa.String(), nullable=True),
    sa.Column('reference_clip_id', sa.String(), nullable=True),
    sa.Column('phase_name', sa.String(), nullable=False),
    sa.Column('start_frame', sa.Integer(), nullable=False),
    sa.Column('end_frame', sa.Integer(), nullable=False),
    sa.Column('detection_method', sa.String(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['reference_clip_id'], ['qb_reference_clips.clip_id'], ),
    sa.ForeignKeyConstraint(['upload_id'], ['uploads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('qb_reference_features',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('clip_id', sa.String(), nullable=False),
    sa.Column('phase_name', sa.String(), nullable=True),
    sa.Column('feature_vector', sa.JSON(), nullable=False),
    sa.Column('embedding_vector', sa.JSON(), nullable=True),
    sa.Column('extracted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['clip_id'], ['qb_reference_clips.clip_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('qb_reference_features')
    op.drop_table('phase_boundaries')
    op.drop_table('analysis_results')
    op.drop_table('uploads')
    op.drop_table('qb_reference_clips')
    # ### end Alembic commands ###
