"""make matched_qb_name nullable

Revision ID: c9b4dcb4a006
Revises: c09fa1120861
Create Date: 2026-09-25 04:51:44.046796

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9b4dcb4a006'
down_revision: Union[str, Sequence[str], None] = 'c09fa1120861'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('analysis_results', 'matched_qb_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('analysis_results', 'matched_qb_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
